context:
  version: "3.0.0"

package:
  name: "ams-python-pth"
  version: ${{ version }}

build:
  skip: 
    - not win

requirements:
  host:
   - python
  run:
    - python

about:
  homepage: https://github.com/anybody/ams-python-pth
  license: MIT
  license_file: LICENSE
  summary: Enables the Python envionments to be used by the AnyBody Modeling System (AMS).
  description: |
    Enables the Python envionment to be used by the AnyBody Modeling System
    (AMS) by providing a Python path that AMS can use to find Python packages.
    It also sets the `ANYBODY_PATH_PYTHONHOME` in the activated environment,
    which tells AMS where to find the Python installation.
  documentation: https://github.com/anybody/ams-python-pth
  repository: https://github.com/anybody/ams-python-pth
