[project]
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ams-python-pth-recipe"
platforms = ["win-64"]
version = "1.0.0"

[tasks]
build = {cmd="rattler-build build --no-include-recipe --recipe=recipe/recipe.yaml"}
upload-with-1pass = "op run --env-file=upload.env -- rattler-build upload anaconda --verbose -o anybody output/win-64/ams-python-pth*.conda"

[dependencies]
rattler-build = "*"
